CREATE TABLE wyborca (
    id int AUTO_INCREMENT PRIMARY KEY,
    imie VARCHAR(25) ,
    nazwisko VARCHAR(25),
    ip VARCHAR(25) UNIQUE,
    pesel VARCHAR(25) UNIQUE
);
CREATE TABLE par (
    PIS INT NOT NULL,
    PO INT NOT NULL,
    PSL INT NOT NULL,
    WIOSNA INT NOT NULL,
    POROZUMIENIE INT NOT NULL,
    LEWICA INT NOT NULL,
    ZIELONI INT NOT NULL,
    UED INT NOT NULL,
    PPS INT NOT NULL,
    suma INT NOT NULL
);

INSERT INTO wyborca (ip,pesel) VALUES (0,0);
INSERT INTO par (PIS,PO,PSL,WIOSNA,POROZUMIENIE,LEWICA,ZIELONI,
UED,PPS,suma) VALUES (0,0,0,0,0,0,0,0,0,0);